version: '3.9'

services:
  postgres:
    #defina as propriedades do seu servidor Posgres

  mongodb:
    #defina as demais propriedades de seu servidor MongoDB. Observe que estamos deixando o volume configurado, pois ele é necessário para inicializar a base e coleção de dados utilizada no projeto
    volumes:
      - ./mongodb-init/init.js:/docker-entrypoint-initdb.d/init.js:ro
      
  python_app:
    build:
      context: ./python_etl
      dockerfile: /docker/Dockerfile
    #defina as propriedades do seu servidor Python  
    depends_on:
      - postgres
      - mongodb   
    

networks:
  #defina sua rede
